server:
  port: 8008

org:
  slf4j:
    simpleLogger:
      defaultLogLevel: debug

spring:
  datasource:
    url: jdbc:postgresql://192.168.246.30:5433/telegram_bot
    username: postgres
    password: postgres
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

nis:
  pro:
    path: /znuny/nph-genericinterface.pl/Webservice/Ticket/

info:
  mail: sales@nis-team.ru
  mail2: info@nis-team.ru
  site: https://nis-pro.ru
  mobile: +7 (495) 775–81–30
  vk: https://vk.com/nis_team
  address: 109316, г.Москва, Волгоградский проспект, д.46Б, корп.1
  desc: Этот бот создан для взаимодействия с информационной системой НИС-Про – программа для бухгалтерского бизнеса

settings:
  array:
    state: open,new,inwork,solved

security:
  login: nispro
  password: nispro

bot:
  name: NISPRO_bot
  token: 5411694794:AAFG6UZ29Z9atazdRIKoMa_kPG93tm0mQhM

#  -Drun.jvmArguments="-Dfile.encoding=UTF-8" -Xverify:none