server:
  port: 8008

org:
  slf4j:
    simpleLogger:
      defaultLogLevel: debug

spring:
  datasource:
    url: jdbc:mysql://192.168.***.***:***/***
    username: ***
    password: ***
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

nis:
  pro:
    path: /otrs/nph-genericinterface.pl/Webservice/Ticket/